name: Issue
about: Testing
title: ''
labels: ['enhancement']
assignees: ''
body:
  - type: input
    attributes:
      label: Do you like testing?
      description: 'yes or no'
    validations:
      required: true
